name: Update

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install

      - name: Update webfontList
        env:
          GOOGLE_FONTS_KEY: ${{ secrets.GOOGLE_FONTS_KEY }}
        run: |
          node playground/update.mjs
          git add .
          git commit -m "Update webfontList"
          git push
