name: Update

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "18"

      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install

      - name: Update webfontList
        env:
          GOOGLE_FONTS_KEY: ${{ secrets.GOOGLE_FONTS_KEY }}
        run: |
          node playground/update.mjs
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore: update webfontList"
          git push
